### ISSUE TITLE
Empty C main function fails to compile

### ISSUE THREAD

**Issue by maxmarsc** [realtime-sanitizer/radsan#25]
Hi ! First of all, thanks a lot for this initiative.

I was checking my custom installation of radsan and discovered that a basic C compilation checks fails when `-fsanitize=realtime` is passed.

Running in the docker image `realtimesanitizer/radsan-clang:latest`

```bash
# C++ main without realtime sanitizer - OK
echo 'int main() { return 0; }' | clang++ -x c - -o /dev/null

# C++ main with realtime sanitizer - OK
echo 'int main() { return 0; }' | clang++ -fsanitize=realtime -x c - -o /dev/null

# C main without realtime sanitizer - OK
echo 'int main() { return 0; }' | clang -x c - -o /dev/null

# C main with realtime sanitizer - Failed
echo 'int main() { return 0; }' | clang -fsanitize=realtime -x c - -o /dev/null
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.radsan.a(radsan_user_interface.cpp.o): in function `std::_Function_handler<radsan::OnErrorAction (), radsan::createErrorActionGetter()::$_1>::_M_invoke(std::_Any_data const&)':
radsan_user_interface.cpp:(.text._ZNSt17_Function_handlerIFN6radsan13OnErrorActionEvEZNS0_23createErrorActionGetterEvE3$_1E9_M_invokeERKSt9_Any_data+0x1c): undefined reference to `std::cout'
/usr/bin/ld: radsan_user_interface.cpp:(.text._ZNSt17_Function_handlerIFN6radsan13OnErrorActionEvEZNS0_23createErrorActionGetterEvE3$_1E9_M_invokeERKSt9_Any_data+0x27): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
/usr/bin/ld: radsan_user_interface.cpp:(.text._ZNSt17_Function_handlerIFN6radsan13OnErrorActionEvEZNS0_23createErrorActionGetterEvE3$_1E9_M_invokeERKSt9_Any_data+0x2e): undefined reference to `std::cin'
/usr/bin/ld: radsan_user_interface.cpp:(.text._ZNSt17_Function_handlerIFN6radsan13OnErrorActionEvEZNS0_23createErrorActionGetterEvE3$_1E9_M_invokeERKSt9_Any_data+0x47): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char> >(std::basic_istream<char, std::char_traits<char> >&, char&)'
/usr/bin/ld: /usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.radsan.a(radsan_user_interface.cpp.o): in function `_GLOBAL__sub_I_radsan_user_interface.cpp':
radsan_user_interface.cpp:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld: radsan_user_interface.cpp:(.text.startup+0x13): undefined reference to `std::ios_base::Init::~Init()'
/usr/bin/ld: /usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.radsan.a(radsan_user_interface.cpp.o):(.data.rel.ro._ZTIZN6radsan23createErrorActionGetterEvE3$_0+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/ld: /usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.radsan.a(radsan_user_interface.cpp.o):(.data.rel.ro._ZTIZN6radsan23createErrorActionGetterEvE3$_1+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/ld: /usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.radsan.a(radsan_user_interface.cpp.o):(.data.rel.ro._ZTIZN6radsan23createErrorActionGetterEvE3$_2+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.radsan.a(radsan_context.cpp.o): in function `radsan::Context::expectNotRealtime(char const*)':
radsan_context.cpp:(.text._ZN6radsan7Context17expectNotRealtimeEPKc+0x52): undefined reference to `std::__throw_bad_function_call()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cjappl** [comment]
Thanks for the report @maxmarsc ! Let me look into it.

**Comment by cjappl** [comment]
I can reproduce on my mac, although the errors are a little different. I think they point to the same issue of a dependency problem on C++ standard library in C linkage. 


```
# Normal clang++ works fine! with C++ 
> echo 'int main() { return 0; }' | clang++  -x c - -o /dev/null -arch arm64

# Radsan clang also needs a c++ standard library, which is surprising and broken! Even without the flag -fsanitize=realtime
> echo 'int main() { return 0; }' | rclang++ -x c - -o /dev/null -arch arm64
ld: library 'c++' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

# with -fsanitize=realtime only works if you pass in a sys root to a C++ standard library. Basic does not work. This may be a problem? Not sure
> echo 'int main() { return 0; }' | rclang++ -fsanitize=realtime -x c - -o /dev/null
ld: library 'c++' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> echo 'int main() { return 0; }' | rclang++ -fsanitize=realtime -x c - -o /dev/null -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk
>


# Normal clang works fine with C code
> echo 'int main() { return 0; }' | clang -x c - -o /dev/null


# Radsan clang fails
> echo 'int main() { return 0; }' | rclang -fsanitize=realtime -x c - -o /dev/null
ld: library 'System' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cjappl** [comment]
OK some good news here, I have up this branch () a version of radsan that no longer dies on c files. If you're stuck and need this for a project (and are OK with the tradeoffs listed) you can use that as a temporary jumping off point.


From that build, regular c files with interceptors work well
```bash
root@5520df3206e2:/my_repo# cat blah.c
#include <stdlib.h>

[[clang::realtime]]
int main(void)
{
    int *p = malloc(10 * sizeof(int));
    (void)p;
    return 0;
}
root@5520df3206e2:/my_repo# clang -fsanitize=realtime blah.c
root@5520df3206e2:/my_repo# ./a.out
Real-time violation: intercepted call to real-time unsafe function `malloc` in real-time context! Stack trace:
    #0 0xaaaaca775f78 in radsan::printStackTrace() /llvm-project/compiler-rt/lib/radsan/radsan_stack.cpp:44:3
    #1 0xaaaaca775dd4 in radsan::Context::expectNotRealtime(char const*) /llvm-project/compiler-rt/lib/radsan/radsan_context.cpp:46:5
    #2 0xaaaaca77681c in expectNotRealtime /llvm-project/compiler-rt/lib/radsan/radsan_interceptors.cpp:39:29
    #3 0xaaaaca77681c in malloc /llvm-project/compiler-rt/lib/radsan/radsan_interceptors.cpp:247:3
    #4 0xaaaaca799adc in main (/my_repo/a.out+0x29adc)
    #5 0xffffa3d373f8  (/lib/aarch64-linux-gnu/libc.so.6+0x273f8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #6 0xffffa3d374c8 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274c8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #7 0xaaaaca775c2c in _start (/my_repo/a.out+0x5c2c)

root@5520df3206e2:/my_repo#
```

And our original problem is fixed:
```
root@5520df3206e2:/my_repo# echo 'int main() { return 0; }' | clang -fsanitize=realtime -x c - -o /dev/null
root@5520df3206e2:/my_repo#
```

**Comment by maxmarsc** [comment]
That's fine, it is not blocking me for now :) thanks for asking though !

**Comment by cjappl** [comment]
This has been fixed in the upstream, and we are unlikely to port it back! Going to close this for now.

Thanks again for reporting it @maxmarsc
